language: python
python:
  - "2.7"
install:
  - pip install zc.buildout==2.3.1
  - pip install setuptools==18.0.1
  - buildout -c .travis.cfg bootstrap
  - buildout -c .travis.cfg -n
script: ./bin/testrunner -m \"gs\\..*\"
